from pathlib import Path
import shutil
import re
import glob
from typing import Optional

from .logger import WranglerLoggable
from .repository import RepositoryManager
from .spec_manager import SpecManager
from .environment import WranglerEnvable
from . import utils
from .constants import DOCKER_BUILD_TIMEOUT


def get_injector(
    repo_manager: RepositoryManager, spec_manager: SpecManager
) -> "SpiInjector":
    """
    Factory method to create a subclass of a Injector which is tuned to
    configure an science-platform-images deployment based on a wrangler spec.

    Conceptually another subclass of Injector could be created to inject into
    a different image building system.
    """
    return SpiInjector(repo_manager, spec_manager)


class SpiInjector(WranglerLoggable, WranglerEnvable):
    """
    A class for interacting with a Science Platform Images (SPI) respository,
    which includes finding extra package requirements for the curated environment
    and also updating the repository deployment with the final package requirements
    generated by the spec.
    """

    _url = "https://github.com/spacetelescope/science-platform-images.git"

    def __init__(
        self,
        repo_manager: RepositoryManager,
        spec_manager: SpecManager,
    ):
        super().__init__()
        self.repo_manager = repo_manager
        self.spec_manager = spec_manager
        self.spi_path = Path(repo_manager.repos_dir) / self.repo_name
        self.deployment_name = self.spec_manager.deployment_name
        self.base_ingest_branch = "origin/main"
        self.ingest_dir = Path("nbw-spec-archive")
        self.archive_dir = Path("nbw-spec-archive")
        self.deployments_path = self.spi_path / "deployments"
        self.deployment_path = self.deployments_path / self.deployment_name
        self.environments_path = self.deployment_path / "environments"

    @property
    def url(self):
        return self.spec_manager.spi.get("repo") or self._url

    @property
    def repo_name(self):
        name = self.url.split("/")[-1]
        return name.split(".")[0]

    @property
    def spec_id(self):
        return self.spec_manager.spec_id

    @property
    def core_name(self):
        """Core name for both submission branch and archived spec,  minus file extension."

        Designed to sort repo spec archive simply into time order with the latest spec last
        and also to be directly traceable to the contents of the spec it names. This enables
        verifying that the image built and tagged corresponds to the submission.

        Based on: submission/current time, sanitized image name, prefix of spec sha256.
        """
        # Replace spaces, dots, etc. with "-".  Preserve case.
        ingestified = re.sub("[^0-9a-zA-Z-]", "-", self.spec_manager.image_name)
        return "-".join(["nbw", utils.hex_time(), ingestified, self.spec_id])

    @property
    def ingest_branch(self):
        """Name of branch that will be PR'ed for this --submit-for-build submission, based on core name."""
        return self.core_name

    @property
    def ingest_name(self) -> str:
        """Name of spec when added to wrangler nbw-spec-archive directory during --submit-for-build,
        traceable to ingest branch, image tag, and PR.
        """
        return self.core_name + ".yaml"

    @property
    def spi_injection_branch_name(self):
        """Name of branch for SPI injection of the spec, based on core name, when no branch
        is explicitly provided provided using --spi-branch."""
        return "spi-" + self.core_name.replace("nbw-", "")

    def copy_file(self, fromfile: Path | str, tofile: Path | str) -> bool:
        fromfile, tofile = str(fromfile), str(tofile)
        self.logger.debug(f"Copying {fromfile} to {tofile}.")
        shutil.copy(fromfile, tofile)
        return True

    def set_wrangler_spec(self) -> bool:
        """Write out the wrangler environment spec with a generic name."""
        out_spec = self.environments_path / "nbw-wrangler-spec.yaml"
        self.logger.info("Saving spec to SPI environments dir: ", out_spec)
        return self.spec_manager.save_spec(out_spec)

    def inject(self, kernel_name: str, env_exports: str) -> bool:
        """
        Performs a placeholder injection of the SPI.
        """
        self.logger.info(
            f"Initiating SPI injection into {self.spi_path} for {self.deployment_name} kernel {kernel_name}..."
        )
        if self.deployment_name != "wrangler":
            kernel_path = self.environments_path / kernel_name
            test_path = kernel_path / "tests"
            env_yml = kernel_path / f"{kernel_name}.yml"
            env_pip = kernel_path / f"{kernel_name}.pip"
            self._inject("test_imports", test_path / "imports")
            # self._inject("test_notebooks", self.test_path / "notebooks")
            self._inject("mamba_spec", env_yml)
            self._inject("pip_compiler_output", env_pip)
        self._inject(
            None, self.deployment_path / "MISSION_VERSION", self.spec_manager.moniker
        )
        self._inject(None, self.environments_path / "nbw-exports.sh", env_exports)
        self._inject(
            None,
            self.environments_path / "common-hints.mamba",
            self.spec_manager.common_mamba_packages,
        )
        self._inject(
            None,
            self.environments_path / "common-hints.pip",
            self.spec_manager.common_pip_packages,
        )
        apt_file = self.environments_path / "apt-packages.txt"
        if self.spec_manager.has_apt_packages:
            self._inject(
                None,
                apt_file,
                self.spec_manager.apt_packages,
            )
        elif apt_file.exists():
            self.logger.info(f"Removing {apt_file} as apt_packages is not in spec.")
            apt_file.unlink()

        aux_sh_file = self.environments_path / "dockerfile-aux.sh"
        if self.spec_manager.dockerfile_aux_sh:
            self._inject(
                None,
                aux_sh_file,
                self.spec_manager.dockerfile_aux_sh,
            )
        elif aux_sh_file.exists():
            self.logger.info(
                f"Removing {aux_sh_file} as dockerfile_aux_sh is not in spec."
            )
            aux_sh_file.unlink()

        self._inject_assets()

        self.spec_manager.save_spec_as(
            self.environments_path / "nbw-wrangler-spec.yaml", add_sha256=True
        )

        return self.logger.info("SPI injection complete.")

    def _inject_assets(self) -> None:
        """Inject assets specified in the spec into the SPI environments directory.

        This copies asset files/directories from their source repositories into
        `environments/assets/` and generates `environments/dockerfile-assets.sh`
        to copy assets to their final destinations inside the container image during Docker build.
        """
        assets = self.spec_manager.assets
        assets_dir = self.environments_path / "assets"
        assets_sh_file = self.environments_path / "dockerfile-assets.sh"

        if not assets:
            return self._clean_asset_injection(assets_dir, assets_sh_file)

        self.logger.info(
            f"Injecting {len(assets)} assets into {self.environments_path}..."
        )
        if assets_dir.exists():
            shutil.rmtree(assets_dir)
        assets_dir.mkdir(parents=True, exist_ok=True)

        script_lines = [
            "#!/usr/bin/env bash",
            "# Generated by nb-wrangler for asset installation during Docker build",
            "set -e",
            "",
        ]
        for idx, asset in enumerate(assets):
            script_lines.extend(
                self._stage_and_build_asset_command(idx, asset, assets_dir)
            )

        self._write_assets_script(assets_sh_file, script_lines)

    def _clean_asset_injection(self, assets_dir: Path, assets_sh_file: Path) -> None:
        """Remove old asset directory and script if no assets are defined."""
        if assets_dir.exists():
            self.logger.info(f"Removing old assets directory {assets_dir}")
            shutil.rmtree(assets_dir)
        if assets_sh_file.exists():
            self.logger.info(f"Removing old dockerfile-assets script {assets_sh_file}")
            assets_sh_file.unlink()

    def _fetch_asset_source(
        self, repo_url: str, ref: Optional[str], source: str
    ) -> Path:
        """Fetch remote repo and return verified source path."""
        repo_path = self.repo_manager._setup_remote_repo(
            repo_url, floating_mode=True, ref=ref
        )
        if not repo_path or not repo_path.exists():
            raise RuntimeError(f"Failed to setup asset repository {repo_url}")
        clean_source = source.rstrip("/").lstrip("/")
        src_path = repo_path / clean_source if clean_source else repo_path
        if not src_path.exists():
            raise RuntimeError(
                f"Asset source path '{source}' not found in {repo_url} at ref '{ref}'"
            )
        return src_path

    def _resolve_asset_sources(
        self, repo_path: Path, repo_url: str, ref: Optional[str], source: str
    ) -> tuple[list[Path], bool]:
        """Resolve source path or glob pattern into a list of matching Paths."""
        if "*" in source or "?" in source:
            clean_pattern = source.lstrip("/")
            full_pattern = str(repo_path / clean_pattern)
            matched_strs = sorted(glob.glob(full_pattern, recursive=True))
            matched_paths = [Path(p) for p in matched_strs if Path(p) != repo_path]
            if not matched_paths:
                raise RuntimeError(
                    f"Asset source pattern '{source}' matched no files in {repo_url} at ref '{ref}'"
                )
            return matched_paths, True
        else:
            src_path = self._fetch_asset_source(repo_url, ref, source)
            return [src_path], False

    def _stage_and_build_asset_command(
        self, idx: int, asset: dict, assets_dir: Path
    ) -> list[str]:
        """Stage a single asset into assets_dir and generate its shell commands."""
        repo_url, ref = asset.get("repo"), asset.get("ref")
        source, destination = asset.get("source"), asset.get("destination")
        if not repo_url or not source or not destination:
            self.logger.warning(f"Asset item {idx} missing required fields. Skipping.")
            return []

        self.logger.info(
            f"Processing asset {idx + 1}: {source} -> {destination} from {repo_url}"
        )
        repo_path = self.repo_manager._setup_remote_repo(
            repo_url, floating_mode=True, ref=ref
        )
        if not repo_path or not repo_path.exists():
            raise RuntimeError(f"Failed to setup asset repository {repo_url}")

        matched_paths, is_glob = self._resolve_asset_sources(
            repo_path, repo_url, ref, source
        )

        stage_item_dir = assets_dir / f"asset_{idx}"
        stage_item_dir.mkdir(parents=True, exist_ok=True)

        if is_glob:
            return self._stage_and_build_glob_asset(
                idx, source, destination, matched_paths, stage_item_dir
            )

        src_path = matched_paths[0]
        staged_dest = stage_item_dir / src_path.name
        rel_staged = f"assets/asset_{idx}/{src_path.name}"

        if src_path.is_dir():
            shutil.copytree(src_path, staged_dest)
            copy_contents_only = (
                source.endswith("/")
                or source.endswith("/*")
                or asset.get("contents_only", False)
            )
            return self._build_directory_asset_cmds(
                idx, source, destination, rel_staged, copy_contents_only
            )
        else:
            shutil.copy2(src_path, staged_dest)
            return self._build_file_asset_cmds(idx, source, destination, rel_staged)

    def _stage_and_build_glob_asset(
        self,
        idx: int,
        source: str,
        destination: str,
        matched_paths: list[Path],
        stage_item_dir: Path,
    ) -> list[str]:
        """Stage glob-matched files/directories and generate installation commands."""
        script_lines = [
            f"# Asset {idx}: glob {source} -> {destination}",
            f'echo "Installing asset pattern {source} ({len(matched_paths)} items) to {destination}..."',
            f'mkdir -p "{destination}"',
        ]
        for src_path in matched_paths:
            staged_dest = stage_item_dir / src_path.name
            rel_staged = f"assets/asset_{idx}/{src_path.name}"
            if src_path.is_dir():
                if staged_dest.exists():
                    shutil.rmtree(staged_dest)
                shutil.copytree(src_path, staged_dest)
                script_lines.append(f'cp -r "{rel_staged}" "{destination}/"')
            else:
                shutil.copy2(src_path, staged_dest)
                script_lines.append(f'cp "{rel_staged}" "{destination}/"')
        script_lines.append("")
        return script_lines

    def _build_directory_asset_cmds(
        self,
        idx: int,
        source: str,
        destination: str,
        rel_staged: str,
        copy_contents_only: bool = True,
    ) -> list[str]:
        """Generate bash lines to install a directory asset."""
        if copy_contents_only:
            cp_cmd = f'cp -r "{rel_staged}"/. "{destination}/"'
        else:
            cp_cmd = f'cp -r "{rel_staged}" "{destination}/"'

        return [
            f"# Asset {idx}: directory {source} -> {destination}",
            f'echo "Installing asset directory {rel_staged} to {destination}..."',
            f'mkdir -p "{destination}"',
            cp_cmd,
            "",
        ]

    def _build_file_asset_cmds(
        self, idx: int, source: str, destination: str, rel_staged: str
    ) -> list[str]:
        """Generate bash lines to install a single file asset."""
        return [
            f"# Asset {idx}: file {source} -> {destination}",
            f'echo "Installing asset file {rel_staged} to {destination}..."',
            f'if [ -d "{destination}" ] || [[ "{destination}" == */ ]]; then',
            f'    mkdir -p "{destination}"',
            f'    cp "{rel_staged}" "{destination}/"',
            "else",
            f'    mkdir -p "$(dirname "{destination}")"',
            f'    cp "{rel_staged}" "{destination}"',
            "fi",
            "",
        ]

    def _write_assets_script(
        self, assets_sh_file: Path, script_lines: list[str]
    ) -> None:
        """Write asset installation script and grant execution permissions."""
        with assets_sh_file.open("w") as f:
            f.write("\n".join(script_lines) + "\n")
        assets_sh_file.chmod(0o755)

    def _inject(
        self,
        field: Optional[str],
        where: str | Path,
        literal: Optional[str | list[str] | dict[str, str]] = None,
    ) -> None:
        if field:
            self.logger.info(f"Injecting field {field} to {where}")
        else:
            self.logger.info(f"Injecting {where}")
        where = Path(where)
        if not where.parent.exists():
            self.logger.warning(
                f"Directory for '{where.parent}' does not exist, skipping injection."
            )
            return
        with where.open("w+") as f:
            if field:
                obj = self.spec_manager.get_output_data(field)
            elif literal is not None:
                obj = literal
            else:
                raise RuntimeError(
                    "Attempt to inject invalid field {field} or literal {literal} to {where}"
                )
            if isinstance(obj, dict):
                utils.get_yaml().dump(obj, f)
            elif isinstance(obj, list):
                f.write("\n".join(obj))
            elif isinstance(obj, str):
                f.write(obj)
            else:
                raise ValueError(f"Unsupported type {type(obj)} for field {field}")

    def branch(self, branch_name: str) -> bool:
        self.logger.info(f"Creating new branch {branch_name} in {self.repo_name}.")
        return self.repo_manager.git_create_branch(self.repo_name, branch_name)

    def add_injected_files(self) -> bool:
        self.logger.info(f"Adding injected files to git in {self.repo_name}.")
        return self.repo_manager.git_add(self.repo_name, "deployments")

    def commit(self, message: str) -> bool:
        self.logger.info(f"Committing changes in {self.repo_name}.")
        return self.repo_manager.git_commit(self.repo_name, message)

    def push(self, branch_name: str) -> bool:
        self.logger.info(f"Pushing branch {branch_name} to remote in {self.repo_name}.")
        return self.repo_manager.git_push(self.repo_name, branch_name)

    def create_pr(self, branch_name: str, message: str) -> bool:
        self.logger.info(
            f"Creating pull request for branch {branch_name} in {self.repo_name}."
        )
        title = f"nb-wrangler: Automated SPI injection for {self.spec_manager.spec_file.name}"
        return self.repo_manager.github_create_pr(
            self.repo_name, self.base_ingest_branch, title, message
        )

    def prune(self) -> bool:
        self.logger.info(f"Pruning Docker SPI images for {self.deployment_name}.")
        result = self.repo_manager.run(
            f"scripts/wrangler-prune {self.deployment_name}",
            check=False,
            cwd=self.spi_path,
            output_mode="uncaught",
        )
        return self.env_manager.handle_result(
            result,
            f"Failed to prune Docker for old {self.deployment_name} images: ",
            f"Pruned Docker to force rebuild of {self.deployment_name} images.",
        )

    def build(self) -> bool:
        self.logger.info(
            f"Building Docker image for {self.deployment_name} in {self.spi_path} with wrangler-build script."
        )
        result = self.repo_manager.run(
            f"scripts/wrangler-build {self.deployment_name}",
            check=False,
            cwd=self.spi_path,
            timeout=DOCKER_BUILD_TIMEOUT,
            output_mode="uncaught",
        )
        return self.env_manager.handle_result(
            result,
            f"Failed to build Docker image for {self.deployment_name} under {self.spi_path}.",
            f"Built Docker image for {self.deployment_name} under {self.spi_path}.",
        )

    def get_spi_requirements(self, kind, glob_patterns: list[Path]) -> list[Path]:
        """Find extra mamba or pip requirements files required by SPI
        environments such as those included in the common/common-env directory
        and/or {deployment}/environments/common-hints.{pip,conda,mamba}. mamba
        packages are typically non-Python packages such as C libraries and
        compiles and install tools.  For Python packages, using pip to install
        them is preferred.
        """

        spi_extra_requirements = []
        for pattern in glob_patterns:
            extras = Path(".").glob(str(pattern))
            for path in extras:
                spi_extra_requirements.append(path)
                self.logger.debug(
                    f"Found SPI {kind} requirements file {path} based on glob '{pattern}'"
                )
        self.logger.info(
            f"Found SPI extra {len(spi_extra_requirements)} {kind} requirements files."
        )
        return spi_extra_requirements

    def find_spi_pip_files(self) -> list[Path]:
        return self.get_spi_requirements(
            "pip",
            [
                self.deployments_path / "common/common-env/*.pip",
                self.deployment_path / "environments/common-hints.pip",
            ],
        )

    def find_spi_mamba_files(self) -> list[Path]:
        return self.get_spi_requirements(
            "mamba",
            [
                self.deployments_path / "common/common-env/*.conda",
                self.deployments_path / "common/common-env/*.mamba",
                self.deployment_path / "environments/common-hints.conda",
                self.deployment_path / "environments/common-hints.mamba",
            ],
        )
